version: "3"

services:
  mymongodb:
    image: mongo:latest
    # restart: always
    container_name: mymongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=devdb
    #   - MONGO_INITDB_ROOT_PASSWORD=devdb123
    ports:
      - 27017:27017
  backend:
    # environment:
    #   - MONGO_DB_HOSTNAME=mymongodb
    build: ./backend
    container_name: backend2
    ports:
      - 8080:8080
    # links:
    #   - mymongodb
    depends_on:
      - mymongodb
  frontend:
    container_name: frontend
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "app/node_modules"
      - "./frontend/:/app"
